services:
  almabundle.twig.indietro_extension:
    class: AlmaBundle\TwigExtension\IndietroTwigExtension
    arguments: [@service_container]
    tags:
      - { name: twig.extension }

  generazione_documenti:
      class: AlmaBundle\Service\GeneratoreDocumenti
      arguments: [@service_container, @twig ]

