<?php

namespace AlmaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * LettoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettoRepository extends EntityRepository
{
    public function getOccupazioneLetto($idLetto, \DateTime $da, \DateTime $a, $prenotazioneId = null){
        $risultato = $this->getPrenotazioneLetto($idLetto,$da,$a,$prenotazioneId);
        if(is_null($risultato)){
            return false;
        }else{
            return true;
        }
    }

    public function getPrenotazioneLetto($idLetto, \DateTime $da, \DateTime $a, $prenotazioneId = null){
        $em = $this->getEntityManager();

        $da_ = $da->format("Y-m-d");
        $a_ = $a->format("Y-m-d");
        $dql = "SELECT p.id FROM AlmaBundle:Letto l
                JOIN l.prenotazioni p
                WHERE l.id = :idLetto AND (
                    (p.dataInizio > :da AND p.dataInizio < :a) OR
                    (p.dataFine > :da AND p.dataFine < :a) OR
                    (p.dataInizio <= :da AND p.dataFine >= :a)
                )";

        if($prenotazioneId != null){
            $dql .= " AND p.id != :prenotazioneId";
        }

        $query = $em->createQuery($dql);
        $query->setParameter("da",$da_);
        $query->setParameter("a",$a_);
        $query->setParameter("idLetto",$idLetto);
        if($prenotazioneId !=null){
            $query->setParameter("prenotazioneId",$prenotazioneId);
        }

        $risultato = $query->getOneOrNullResult();
        return is_null($risultato) ? null : $risultato["id"];
    }
}
