<?php

namespace AlmaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrenotazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RicevutaRepository extends EntityRepository
{

    public function getUltimaRicevuta(){
        $em = $this->getEntityManager();

        $dql = "SELECT r FROM AlmaBundle:Ricevuta r ORDER BY r.data";

        $query = $em->createQuery($dql);

        $risultato = $query->setMaxResults(1)->getOneOrNullResult();

        return $risultato;
    }

    public function getProssimoNumero(){
        $ultimaRicetua = $this->getUltimaRicevuta();
        return $ultimaRicetua == null ? 1 : $ultimaRicetua->getNumero()+1;
    }
}
