tipocamera:
    path:     /
    defaults: { _controller: "AlmaBundle:TipoCamera:index" }

tipocamera_show:
    path:     /{id}/show
    defaults: { _controller: "AlmaBundle:TipoCamera:show" }

tipocamera_new:
    path:     /new
    defaults: { _controller: "AlmaBundle:TipoCamera:new" }

tipocamera_create:
    path:     /create
    defaults: { _controller: "AlmaBundle:TipoCamera:create" }
    methods:  POST

tipocamera_edit:
    path:     /{id}/edit
    defaults: { _controller: "AlmaBundle:TipoCamera:edit" }

tipocamera_update:
    path:     /{id}/update
    defaults: { _controller: "AlmaBundle:TipoCamera:update" }
    methods:  [POST, PUT]

tipocamera_delete:
    path:     /{id}/delete
    defaults: { _controller: "AlmaBundle:TipoCamera:delete" }
    methods:  [GET]
