<?php

namespace Geo\GeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CodiceCatastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodiceCatastoRepository extends EntityRepository
{
    
    public function codiciCatastoList($codice_istat, $data_riferimento = null) {
		$qb = $this->createQueryBuilder('c');
        
        $qb->where('c.codice_istat = :codice_istat')
           ->setParameter('codice_istat', $codice_istat);      
        
		$qb->orderBy('c.data_soppressione', 'ASC');
        $codici_catasto = $qb->getQuery()->getResult();
        
        if ($data_riferimento instanceof \DateTime) {
            $codice_catasto_corrispondente = null;
            foreach ($codici_catasto as $codice_catasto) {
                if (is_null($codice_catasto_corrispondente)) {
                    $codice_catasto_corrispondente = $codice_catasto;
                } else {
                    if (!is_null($codice_catasto->getDataIstituzione())) {
                        if ($data_riferimento <= $codice_catasto->getDataIstituzione()) {
                            $codice_catasto_corrispondente = $codice_catasto;
                        }
                        
                        if ($data_riferimento > $codice_catasto->getDataIstituzione() && $data_riferimento <= $codice_catasto->getDataSoppressione()) {
                            $codice_catasto_corrispondente = $codice_catasto;
                        }
                        
                    }
                }
            }
            
            return array($codice_catasto_corrispondente);
        } else {
            return $codici_catasto;
        }
    }
    
    public function getGeoByCodiceCatasto($codice_catasto) {
        $qb = $this->createQueryBuilder('c');
        
        $qb->where('c.codice_catasto = :codice_catasto')
           ->setParameter('codice_catasto', $codice_catasto);
        
        try {
            $codice_istat = $qb->getQuery()->getSingleResult();

            if (\strlen($codice_istat->getCodiceIstat()) > 5) {
                $query = "SELECT c FROM Geo\GeoBundle:GeoComune c WHERE c.codice_completo='".$codice_istat->getCodiceIstat()."'";      
            } else {
                $query = "SELECT s FROM Geo\GeoBundle:GeoStato s WHERE s.codice='".$codice_istat->getCodiceIstat()."'";
            }
            
            return $this->getEntityManager()->createQuery($query)->getSingleResult();

        } catch (\Exception $e) {
            return null;
        }
        
        
    }
}